export const projects = [
  {
    title: 'SamShare',
    description: "A simple social media photo sharing app, with CRUD functionality, Google Authentication and Sanity.io for content management, hosted on Netlify.",
    image: '/images/samshare.png',
    tags: ['TailwindCSS', 'React', 'Sanity.io'],
    source: 'https://github.com/sentinel-sam/samshare_frontend',
    visit: 'https://samshare.netlify.app/',
    id: 0,
  },
  {
    title: 'YelpCamp',
    description: "A simple web app, with CRUD functionality, using Mongoose, ExpressJS server, EJS templating language, PassportJS authentication middleware, Joi JS, Cloudinary for content management, hosted on Heroku.",
    image: '/images/yelpcamp.png',
    tags: ['JavaScript', 'NodeJS', 'MongoDB'],
    source: 'https://github.com/sentinel-sam/yelpcamp',
    visit: 'http://calm-headland-65887.herokuapp.com/',
    id: 0,
  },
  {
    title: 'IP Address Tracker',
    description: "A simple web app that displays the location of the user's Network IP Address or a searched IP Address, using ipify.org, hosted on Netlify.",
    image: '/images/ip-tracker.png',
    tags: ['JavaScript', 'Leaflet.js'],
    source: 'https://github.com/sentinel-sam/ip-address-tracker-js',
    visit: 'https://sam-ip-address-tracker-js.netlify.app/',
    id: 1,
  },
  {
    title: 'Scientific Calculator',
    description: "A scientific calculator with complex mathematical and trigonometrical functions.",
    image: '/images/sci-calc.png',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
    source: 'https://github.com/sentinel-sam/js-scientific-calc',
    visit: 'https://samio-js-scientific-calculator.netlify.app/',
    id: 2,
  },
  {
    title: 'Countdown Timer',
    description: "Select a date, and set up a countdown timer.",
    image: '/images/countdown.png',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
    source: 'https://github.com/sentinel-sam/countdown-timer',
    visit: 'https://sameo-countdown-timer.netlify.app/',
    id: 3,
  },
  {
    title: 'Cloud9ine',
    description: "A weather app, making API calls to Open Weather, hosted on Firebase",
    image: '/images/cloud.png',
    tags: ['CSS3', 'JavaScript', 'Firebase'],
    source: 'https://github.com/sentinel-sam/weather-app-v2',
    visit: 'https://weather-app-cloud9.web.app/',
    id: 3,
  },
];
